// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn2_MzvDpmG-88LA8j_5Zxf91DeufGDdc',
    appId: '1:342874966385:web:0989c5be9d4fbd628d4ed0',
    messagingSenderId: '342874966385',
    projectId: 'e-commerce-app-13160',
    authDomain: 'e-commerce-app-13160.firebaseapp.com',
    storageBucket: 'e-commerce-app-13160.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3-1DmjRu9GKlfZeJ6lUWA4wtiqcdYc0A',
    appId: '1:342874966385:android:2f3c9bf5ea6124458d4ed0',
    messagingSenderId: '342874966385',
    projectId: 'e-commerce-app-13160',
    storageBucket: 'e-commerce-app-13160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL5puLZ_Q5GDW8O1RdwhQUyFlIp5hz9II',
    appId: '1:342874966385:ios:57d3c4f733277d128d4ed0',
    messagingSenderId: '342874966385',
    projectId: 'e-commerce-app-13160',
    storageBucket: 'e-commerce-app-13160.appspot.com',
    iosClientId: '342874966385-ioi2rbili2fq5ati7a1vv8scam81uc3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
